-- Create CITIES table
CREATE TABLE CITIES (
    CITY CHAR(20),
    STATE CHAR(20),
    PRIMARY KEY (CITY, STATE)
);

-- Create WAREHOUSES table
CREATE TABLE WAREHOUSES (
    WID INTEGER,
    WNAME CHAR(30),
    LOCATION CHAR(20),
    CITY CHAR(20),
    STATE CHAR(20),
    PRIMARY KEY (WID),
    FOREIGN KEY (CITY, STATE) REFERENCES CITIES(CITY, STATE)
);

-- Create STORES table
CREATE TABLE STORES (
    SID INTEGER,
    STORE_NAME CHAR(20),
    LOCATION_CITY CHAR(20),
    CITY CHAR(20),
    STATE CHAR(20),
    PRIMARY KEY (SID),
    FOREIGN KEY (LOCATION_CITY) REFERENCES CITIES(CITY),
    FOREIGN KEY (CITY, STATE) REFERENCES CITIES(CITY, STATE)
);

-- Create CUSTOMER table
CREATE TABLE CUSTOMER (
    CNO INTEGER,
    CNAME CHAR(50),
    ADDR VARCHAR(50),
    CU_CITY CHAR(20),
    CITY CHAR(20),
    STATE CHAR(20),
    PRIMARY KEY (CNO),
    FOREIGN KEY (CU_CITY) REFERENCES CITIES(CITY),
    FOREIGN KEY (CITY, STATE) REFERENCES CITIES(CITY, STATE)
);

-- Create ORDERS table
CREATE TABLE ORDERS (
    ONO INT,
    ODATE DATE,
    CNO INTEGER,
    PRIMARY KEY (ONO),
    FOREIGN KEY (CNO) REFERENCES CUSTOMER(CNO)
);

-- Create ITEMS table
CREATE TABLE ITEMS (
    ITEMNO INTEGER,
    DESCRIPTION TEXT,
    WEIGHT DECIMAL(5,2),
    COST DECIMAL(5,2),
    PRIMARY KEY (ITEMNO)
);

-- Create ORDER_ITEMS table for Many-to-Many relationship between ITEMS and ORDERS
CREATE TABLE ORDER_ITEMS (
    ONO INT,
    ITEMNO INTEGER,
    ORDERED_QUANTITY INTEGER,
    PRIMARY KEY (ONO, ITEMNO),
    FOREIGN KEY (ONO) REFERENCES ORDERS(ONO),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS(ITEMNO)
);

-- Create STORE_ITEMS table for Many-to-Many relationship between STORES and ITEMS
CREATE TABLE STORE_ITEMS (
    SID INTEGER,
    ITEMNO INTEGER,
    QUANTITY INTEGER,
    PRIMARY KEY (SID, ITEMNO),
    FOREIGN KEY (SID) REFERENCES STORES(SID),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS(ITEMNO)
);
-- 1
SELECT ITEMNO, DESCRIPTION, WEIGHT
FROM ITEMS
WHERE WEIGHT = (SELECT MIN(WEIGHT) FROM ITEMS);

-- 2
SELECT DISTINCT WID, WNAME, LOCATION
FROM WAREHOUSES
WHERE CITY = 'Pune';

-- 3
SELECT I.ITEMNO, I.DESCRIPTION, OI.ORDERED_QUANTITY
FROM CUSTOMER C
JOIN ORDERS O ON C.CNO = O.CNO
JOIN ORDER_ITEMS OI ON O.ONO = OI.ONO
JOIN ITEMS I ON OI.ITEMNO = I.ITEMNO
WHERE C.CNAME = 'Mr. Patil';

-- 4
SELECT W.WID, W.WNAME, W.LOCATION, COUNT(S.SID) AS STORE_COUNT
FROM WAREHOUSES W
JOIN STORES S ON W.WID = S.WID
GROUP BY W.WID, W.WNAME, W.LOCATION
ORDER BY STORE_COUNT DESC
LIMIT 1;

-- 5
SELECT ITEMNO, DESCRIPTION
FROM ITEMS
WHERE ITEMNO = (
    SELECT ITEMNO
    FROM ORDER_ITEMS
    GROUP BY ITEMNO
    ORDER BY COUNT(ONO)
    LIMIT 1
);

-- 6
SELECT C.CNO, C.CNAME, O.ONO, O.ODATE, I.ITEMNO, I.DESCRIPTION, OI.ORDERED_QUANTITY
FROM CUSTOMER C
JOIN ORDERS O ON C.CNO = O.CNO
JOIN ORDER_ITEMS OI ON O.ONO = OI.ONO
JOIN ITEMS I ON OI.ITEMNO = I.ITEMNO;
